### ISSUE TITLE
Fix TODOs in meta document

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Standard-SSOT#6]
https://github.com/IATI/IATI-Developer-Documentation/blob/master/ssot/proposal.rst
- [x] Discuss changes to codelists
- [x] Make ruleset notes accessible (password needed now)
- [x] Decide what rules we should have.
- [x] Generated repositories above still are under Bjwebb, not IATI
- [x] Determine when feature branches should be used and when/if committing directly to the main branches is appropriate.
- [x] Think about how GitHub issues fits in with our current use of the knowledge base
- [x] Decide if custom labels make sense, then add them to all SSOT repositories.
- [x] Determine which codelists are functional codelists.
- [x] Decide approach on patch release
- [x] Discuss whether GitHub should be the preferred place to fetch machine readable data

**Comment by Bjwebb** [comment]
Note on labels: [IATI-Schemas](https://github.com/IATI/IATI-Schemas/issues) has an extra 'verify and close' label.

**Comment by Bjwebb** [comment]
Note that this document has now moved to https://github.com/IATI/IATI-Developer-Documentation/blob/master/ssot/proposal.rst

(In this commit https://github.com/IATI/IATI-Standard-SSOT/commit/b7201077ca193b6722441fb260758e42b05b5c3e )
